import type { Metadata } from "next";
import { ENTITY_NAME, AI_DISCLOSURE_LABEL, LEGAL_EMAIL } from "@/lib/site-config";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "AI Disclosure",
  description: `AI use and disclosure policy for ${ENTITY_NAME}`,
};

const EFFECTIVE_DATE = "2026-05-05";

export default function AiDisclosurePage() {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "4rem 1.5rem" }}>
      <h1 style={{ marginBottom: "0.5rem" }}>AI Disclosure</h1>
      <p style={{ color: "var(--text-muted)", marginBottom: "2.5rem", fontSize: "0.875rem" }}>
        Effective: {EFFECTIVE_DATE} &nbsp;|&nbsp; Entity: {ENTITY_NAME}
      </p>

      {/* Prominent disclosure box */}
      <div
        style={{
          background: "rgba(129,140,248,0.1)",
          border: "1px solid rgba(129,140,248,0.4)",
          borderRadius: 10,
          padding: "1.25rem 1.5rem",
          marginBottom: "2.5rem",
          fontSize: "0.95rem",
          color: "var(--text-primary)",
          lineHeight: 1.6,
        }}
      >
        🤖 <strong>Notice:</strong> {AI_DISCLOSURE_LABEL}
      </div>

      <Section title="1. Where AI Is Used">
        <p>
          {ENTITY_NAME} uses artificial intelligence tools as part of the
          following activities:
        </p>
        <ul>
          <li><strong>Content creation:</strong> Some blog articles, guides, and knowledge-base entries are written or refined with AI assistance. These are labelled &quot;AI-assisted&quot; where present.</li>
          <li><strong>Product generation:</strong> Certain digital products (prompt packs, ebooks, scripts) in StoreX are generated or drafted with AI tools, then reviewed by an operator before publishing. These are labelled &quot;AI-assisted&quot; on the product page.</li>
          <li><strong>AI Lab tools:</strong> The Forge provides access to AI-powered workflow and automation tools. Outputs from these tools are generated by AI models and should be reviewed before use in production.</li>
          <li><strong>Virtual Eyes:</strong> Image analysis features use AI vision models. Results are provided for informational purposes only.</li>
        </ul>
      </Section>

      <Section title="2. Labelling Practice">
        <p>
          Content and products that are AI-generated or AI-assisted are labelled
          with the tag <strong>&quot;AI-assisted&quot;</strong> wherever they appear in
          the Store and Knowledge Base. This label indicates that AI tools
          contributed to the creation of the item, even if a human reviewed and
          approved the final output.
        </p>
      </Section>

      <Section title="3. Limitations and Accuracy">
        <p>
          AI-generated content can contain factual errors, outdated information,
          hallucinations, or bias. {ENTITY_NAME} does its best to review
          AI-generated material before publishing, but we cannot guarantee
          accuracy. You should independently verify any critical information
          before acting on it.
        </p>
        <p>
          AI outputs are not a substitute for professional, legal, medical,
          financial, or security advice. Consult a qualified professional for
          decisions with material consequences.
        </p>
      </Section>

      <Section title="4. Your Responsibility">
        <p>
          By using AI tools on this Site, you acknowledge that you are
          responsible for reviewing and validating outputs before using them in
          any real-world context. {ENTITY_NAME} provides AI tools &quot;as is&quot; and
          accepts no liability for actions taken based on AI-generated content.
        </p>
      </Section>

      <Section title="5. Security Content Notice">
        <p>
          Security research content on this Site — including any AI-generated
          threat models or educational material — is intended for{" "}
          <strong>educational and defensive purposes only</strong>. It must not
          be used to conduct attacks on systems you do not own or have explicit
          written authorisation to test.
        </p>
      </Section>

      <Section title="6. Updates to This Policy">
        <p>
          This disclosure will be updated as new AI capabilities are added to
          the platform. Material changes will be announced via the Site.
        </p>
      </Section>

      <Section title="7. Questions">
        <p>
          For questions about our AI use, contact{" "}
          <a href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</a>.
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: "2rem" }}>
      <h2 style={{ fontSize: "1.1rem", marginBottom: "0.75rem", color: "var(--accent)" }}>
        {title}
      </h2>
      <div style={{ color: "var(--text-secondary)", lineHeight: 1.7, display: "flex", flexDirection: "column", gap: "0.5rem" }}>
        {children}
      </div>
    </section>
  );
}
